{
  "openapi": "3.0.3",
  "info": {
    "title": "Test Restful Api",
    "version": "1",
    "description": "test open api",
    "termsOfService": "www.google.com",
    "contact": {
      "name": "yayaya123",
      "email": "yayaya@gmail.com",
      "url": "www.google.com"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://apache.org"
    }
  },
  "servers": [
    {
      "description": "Test rest api server",
      "url": "https://{environment}.testapi.com/api/v1",
      "variables": {
        "environment": {
          "description": "server environment",
          "default": "dev",
          "enum": [
            "dev",
            "prod"
          ]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "postman doc",
    "url": "https://youtube.com"
  },
  "paths": {
    "/test-api": {
      "get": {
        "security": [
          {
            "testAuth": []
          }
        ],
        "tags": [
          "test"
        ],
        "summary": "Get all ex test",
        "description": "get all active test",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "required": false,
            "description": "is include done",
            "schema": {
              "type": "boolean",
              "nullable": true,
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "filter test by name",
            "schema": {
              "type": "string",
              "nullable": true,
              "minLength": 1,
              "maxLength": 100
            }
          }
        ],
        "responses": {
          "200": {
            "description": "get all test data success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/listTest"
                },
                "examples": {
                  "success": {
                    "description": "Get all data success",
                    "value": [
                      {
                        "id": 1,
                        "name": "Firman",
                        "age": 15,
                        "hobbies": [
                          "game",
                          "tidur"
                        ]
                      },
                      {
                        "id": 2,
                        "name": "lala yeye",
                        "age": 17,
                        "hobbies": [
                          "game",
                          "tidur"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "testAuth": []
          }
        ],
        "tags": [
          "test"
        ],
        "summary": "create new data test",
        "description": "create new data test",
        "requestBody": {
          "required": true,
          "content": {
            "application-json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "age": {
                    "type": "integer",
                    "format": "int32",
                    "default": 1,
                    "required": [
                      "true"
                    ]
                  },
                  "hobbies": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                      "type": "string",
                      "minLength": 1
                    }
                  }
                }
              },
              "examples": {
                "java": {
                  "value": {
                    "name": "Firman",
                    "age": 24,
                    "hobbies": [
                      "game",
                      "tidur"
                    ]
                  },
                  "description": "examples reqbody"
                },
                "php": {
                  "value": {
                    "name": "lala yeye",
                    "age": 26,
                    "hobbies": [
                      "a",
                      "b"
                    ]
                  },
                  "description": "examples reqbody"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "create data test success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "number",
                        "format": "int32"
                      },
                      "name": {
                        "type": "string"
                      },
                      "age": {
                        "type": "integer",
                        "format": "int32"
                      },
                      "hobbies": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "create data test success",
                    "value": [
                      {
                        "id": 3,
                        "name": "NameTest",
                        "age": 35,
                        "hobbies": [
                          "makan",
                          "jajan"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/test-api/{id}": {
      "put": {
        "security": [
          {
            "testAuth": []
          }
        ],
        "tags": [
          "test"
        ],
        "summary": "update data test by id",
        "description": "update data test by id",
        "parameters": [
          {
            "$ref": "#/components/parameters/testID"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application-json": {
              "schema": {
                "$ref": "#/components/schemas/createUpdateTest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "update data test success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/listTest"
                  }
                },
                "examples": {
                  "success": {
                    "description": "update data test success",
                    "value": [
                      {
                        "id": 3,
                        "name": "NameTest",
                        "age": 35,
                        "hobbies": [
                          "makan",
                          "jajan"
                        ]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "testAuth": []
          }
        ],
        "tags": [
          "test"
        ],
        "summary": "delete data test by id",
        "description": "delete data test by id",
        "parameters": [
          {
            "$ref": "#/components/parameters/testID"
          }
        ],
        "responses": {
          "200": {
            "description": "delete data test success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "description": "delete data test success",
                    "value": true
                  }
                }
              }
            }
          },
          "404": {
            "description": "delete data test failed",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "description": "delete data test failed",
                    "value": false
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "testAuth": {
        "description": "Test Post ",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "parameters": {
      "testID": {
        "name": "id",
        "in": "path",
        "description": "id for delete",
        "required": true,
        "schema": {
          "type": "string"
        },
        "examples": {
          "java": {
            "description": "example parameter",
            "value": "1"
          },
          "php": {
            "description": "example parameter",
            "value": "2"
          }
        }
      }
    },
    "schemas": {
      "test": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "minLength": 1
          },
          "age": {
            "type": "integer",
            "format": "int32",
            "default": 1,
            "required": [
              "true"
            ]
          },
          "hobbies": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "createUpdateTest": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "age": {
            "type": "integer",
            "format": "int32",
            "default": 1,
            "required": [
              "true"
            ]
          },
          "hobbies": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        }
      },
      "listTest": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/test"
        }
      }
    }
  }
}